"""
Media Blitz Tool - V6.25
The Plainview Protocol

Radio station directory, call-in scripts, X/Twitter sync,
and recording uploads for the Activism Hub.

"The Labyrinth hates noise. Speak loud, speak true."
"""

import streamlit as st
from datetime import datetime
from typing import Dict, List, Any
import urllib.parse

NY_RADIO_STATIONS = [
    {"name": "WABC 770 AM", "type": "Talk Radio", "region": "NYC Metro", "phone": "(212) 613-7770", "twitter": "@77aboradio", "coverage": "5M+"},
    {"name": "WNYC 93.9 FM", "type": "Public Radio", "region": "NYC Metro", "phone": "(646) 829-4000", "twitter": "@WNYC", "coverage": "1M+"},
    {"name": "WOR 710 AM", "type": "News/Talk", "region": "NYC Metro", "phone": "(212) 642-4533", "twitter": "@710WOR", "coverage": "3M+"},
    {"name": "WCBS 880 AM", "type": "News", "region": "NYC Metro", "phone": "(212) 975-4321", "twitter": "@wcaboradio", "coverage": "2M+"},
    {"name": "1010 WINS", "type": "News", "region": "NYC Metro", "phone": "(212) 315-7000", "twitter": "@1010WINS", "coverage": "2M+"},
    {"name": "WFAN 660 AM", "type": "Sports/Talk", "region": "NYC Metro", "phone": "(212) 314-9326", "twitter": "@WFAN660", "coverage": "2M+"},
    {"name": "WXXA-FM Albany", "type": "News/Talk", "region": "Capital Region", "phone": "(518) 862-1023", "twitter": "@FOX23News", "coverage": "500K"},
    {"name": "WHAM 1180 AM", "type": "News/Talk", "region": "Rochester", "phone": "(585) 454-4884", "twitter": "@WHAM1180", "coverage": "400K"},
    {"name": "WBEN 930 AM", "type": "News/Talk", "region": "Buffalo", "phone": "(716) 843-0930", "twitter": "@NewsRadio930", "coverage": "600K"},
    {"name": "WSYR 570 AM", "type": "News/Talk", "region": "Syracuse", "phone": "(315) 472-0222", "twitter": "@NewsRadio570", "coverage": "350K"},
    {"name": "WIBX 950 AM", "type": "News/Talk", "region": "Utica", "phone": "(315) 797-1330", "twitter": "@WIBX950", "coverage": "150K"},
    {"name": "WAMC 90.3 FM", "type": "Public Radio", "region": "Capital Region", "phone": "(800) 323-9262", "twitter": "@WAMCRadio", "coverage": "300K"},
    {"name": "WRVO 89.9 FM", "type": "Public Radio", "region": "Central NY", "phone": "(315) 312-3690", "twitter": "@WRVONews", "coverage": "200K"},
    {"name": "WDST 100.1 FM", "type": "Community", "region": "Hudson Valley", "phone": "(845) 679-7266", "twitter": "@RadioWoodstock", "coverage": "100K"},
    {"name": "WLIR 107.1 FM", "type": "Talk", "region": "Long Island", "phone": "(516) 829-1071", "twitter": "@WLIR1071", "coverage": "400K"}
]

RADIO_SCRIPT_TEMPLATE = """
🎙️ VOICES OF ACCOUNTABILITY — Radio Call-In Script

═══════════════════════════════════════════════════════════════════

PART 1: THE HOOK (30 Seconds)
"Hi, my name is {caller_name} from {town}. I'm calling because I just added 
my {relationship}'s name to the Victim's Memorial Registry on the Plainview 
Protocol. Like thousands of others, I lost them in a nursing home during the 
Cuomo administration, and I'm here to say that the 'Labyrinth' of silence ends now."

PART 2: THE PERSONAL PIVOT (30-45 Seconds)
"My {loved_one_name} wasn't just a statistic. They were {legacy_statement}. 
They died because of executive orders that prioritized politics over senior 
safety. Now, as Andrew Cuomo tries to use his millions in campaign funds to 
buy a 2026 comeback, my family is left with an empty chair and zero answers."

PART 3: THE DEMAND (15 Seconds)
"We aren't just asking for an apology; we are demanding an audit. We want to 
know if the money fueling this 2026 campaign was built on the back of the 
same administration that masked the true death toll of our seniors. 
No transparency, no vote."

PART 4: THE CALL TO ACTION (15 Seconds)
"If you lost someone, go to plainviewprotocol.com. Sign the affidavit, add 
your loved one's story to the Registry, and join the 3,143 County Sentinels. 
We are the audit the Labyrinth never saw coming. Thank you."

═══════════════════════════════════════════════════════════════════

Generated by The Plainview Protocol — Media Blitz Tool V6.25
{timestamp}
"""

def generate_radio_script(
    caller_name: str,
    town: str,
    relationship: str,
    loved_one_name: str,
    legacy_statement: str
) -> str:
    """Generate personalized radio call-in script."""
    timestamp = datetime.now().strftime("%B %d, %Y")
    
    return RADIO_SCRIPT_TEMPLATE.format(
        caller_name=caller_name,
        town=town,
        relationship=relationship,
        loved_one_name=loved_one_name,
        legacy_statement=legacy_statement,
        timestamp=timestamp
    ).strip()

def generate_twitter_post(station_handle: str, caller_name: str) -> str:
    """Generate X/Twitter post for radio call-in."""
    post = f"""I just called {station_handle} to demand a #CuomoAudit2026.

My family lost someone in a NY nursing home during the March 25 directive. We're not asking for apologies—we're demanding transparency.

Join us at plainviewprotocol.com

#SeniorJustice #NYAccountability"""
    return post

def get_twitter_share_url(text: str) -> str:
    """Generate Twitter share URL."""
    encoded_text = urllib.parse.quote(text)
    return f"https://twitter.com/intent/tweet?text={encoded_text}"

def render_media_blitz():
    """Render the Media Blitz dashboard."""
    st.header("🎙️ Media Blitz Tool — V6.25")
    st.caption("Voices of Accountability: Radio Outreach for Families")
    
    st.info("""
    *"The Labyrinth hates noise. When thousands of families tell their stories 
    on the airwaves, the shadows disappear. Speak loud, speak true, and demand 
    the audit. Your voice is the Cannon."*
    
    — Russell David Nomer, Founder
    """)
    
    st.divider()
    
    col1, col2, col3 = st.columns(3)
    col1.metric("📻 NY Stations", len(NY_RADIO_STATIONS))
    col2.metric("📍 Regions Covered", 7)
    col3.metric("👥 Combined Reach", "15M+")
    
    st.divider()
    
    tabs = st.tabs(["📻 Radio Directory", "🎙️ Script Generator", "🐦 X/Twitter Sync", "🎤 Recording Upload"])
    
    with tabs[0]:
        st.subheader("📻 New York Radio Station Directory")
        st.caption("Call-in numbers for news and talk radio across the state")
        
        region_filter = st.selectbox(
            "Filter by Region:",
            ["All Regions", "NYC Metro", "Capital Region", "Rochester", "Buffalo", "Syracuse", "Utica", "Hudson Valley", "Long Island", "Central NY"]
        )
        
        filtered_stations = NY_RADIO_STATIONS if region_filter == "All Regions" else [
            s for s in NY_RADIO_STATIONS if s["region"] == region_filter
        ]
        
        for station in filtered_stations:
            with st.expander(f"📻 {station['name']} — {station['region']}"):
                col1, col2 = st.columns(2)
                
                with col1:
                    st.markdown(f"**Type:** {station['type']}")
                    st.markdown(f"**Phone:** {station['phone']}")
                    st.markdown(f"**Coverage:** {station['coverage']} listeners")
                
                with col2:
                    st.markdown(f"**Twitter:** {station['twitter']}")
                    
                    twitter_text = generate_twitter_post(station['twitter'], "a concerned citizen")
                    twitter_url = get_twitter_share_url(twitter_text)
                    st.link_button(f"🐦 Tag {station['name']} on X", twitter_url)
    
    with tabs[1]:
        st.subheader("🎙️ Radio Call-In Script Generator")
        st.caption("Personalize your accountability message")
        
        with st.form("script_form"):
            col1, col2 = st.columns(2)
            
            with col1:
                caller_name = st.text_input("Your Name")
                town = st.text_input("Your Town/City")
                relationship = st.selectbox(
                    "Relationship to Loved One",
                    ["Mother", "Father", "Grandmother", "Grandfather", "Spouse", "Aunt", "Uncle"]
                )
            
            with col2:
                loved_one_name = st.text_input("Loved One's Name")
                legacy_statement = st.text_area(
                    "One sentence about their life/legacy",
                    placeholder="e.g., 'a retired teacher who spent 40 years educating children'"
                )
            
            submitted = st.form_submit_button("🎙️ Generate My Script", use_container_width=True)
        
        if submitted and caller_name and loved_one_name:
            script = generate_radio_script(
                caller_name,
                town or "New York",
                relationship,
                loved_one_name,
                legacy_statement or "a beloved member of our family"
            )
            
            st.text_area("Your Personalized Script", script, height=400)
            
            st.download_button(
                "📥 Download Script",
                script,
                file_name="radio_callin_script.txt",
                mime="text/plain"
            )
    
    with tabs[2]:
        st.subheader("🐦 One-Click X/Twitter Sync")
        st.caption("Amplify your call with #CuomoAudit2026")
        
        st.markdown("**Select a station you called:**")
        
        selected_station = st.selectbox(
            "Station:",
            options=range(len(NY_RADIO_STATIONS)),
            format_func=lambda i: NY_RADIO_STATIONS[i]["name"]
        )
        
        station = NY_RADIO_STATIONS[selected_station]
        caller = st.text_input("Your Name (for the post)", key="twitter_caller")
        
        if caller:
            twitter_text = generate_twitter_post(station['twitter'], caller)
        else:
            twitter_text = generate_twitter_post(station['twitter'], "a concerned citizen")
        
        st.text_area("Preview Post:", twitter_text, height=150)
        
        twitter_url = get_twitter_share_url(twitter_text)
        st.link_button("🐦 Post to X (Twitter)", twitter_url, use_container_width=True)
        
        st.divider()
        
        st.markdown("**Hashtags for Maximum Reach:**")
        st.code("#CuomoAudit2026 #SeniorJustice #NYAccountability #NursingHomeJustice #PlainviewProtocol")
    
    with tabs[3]:
        st.subheader("🎤 Recording Upload")
        st.caption("Share your call-in recording with fellow Sentinels")
        
        st.warning("**Privacy Notice:** By uploading, you confirm the recording is yours and consent to sharing it publicly.")
        
        uploaded_file = st.file_uploader(
            "Upload your radio call-in recording",
            type=["mp3", "wav", "m4a", "ogg"],
            help="Audio files only (MP3, WAV, M4A, OGG)"
        )
        
        if uploaded_file:
            st.audio(uploaded_file)
            
            call_station = st.text_input("Which station did you call?")
            call_date = st.date_input("Date of call")
            
            if st.button("📤 Submit to Activism Hub", use_container_width=True):
                st.success("✅ Recording submitted! It will appear in the Activism Hub after review.")
                st.balloons()
        
        st.divider()
        
        st.markdown("**Recent Submissions:**")
        st.info("Be the first Sentinel to upload a recording! Your voice inspires others.")
    
    with st.expander("ℹ️ Transparency: Media Outreach Guidelines"):
        st.markdown("""
        **Best Practices:**
        - Call during live shows for maximum impact
        - Keep to the 2-minute script format
        - Stay calm and factual—cite specific dates and reports
        - Thank the host for their time
        
        **Legal Notes:**
        - One-party consent applies in NY (you can record your own calls)
        - All statements should be factual and documented
        - Avoid defamation—stick to public record findings
        
        **Why This Works:**
        By using the Victim's Memorial Registry stories, you move from abstract 
        political criticism to unimpeachable moral testimony. Radio hosts and 
        audiences cannot ignore a citizen who names a specific victim and facility 
        while citing the Plainview Protocol's forensic data.
        """)
    
    st.divider()
    
    st.markdown("""
    **🏛️ The Sentinel's Voice:**
    
    Radio reaches millions who never visit websites. Your 2-minute call-in can 
    shift public discourse and force journalists to cover the audit demand. 
    The Labyrinth operates in silence—break it with your voice.
    
    *Speak loud, speak true, and demand the audit.*
    """)
